#!/bin/bash
# Try Google Maven directly for AndroidX deps
# Google Maven URL pattern: https://dl.google.com/dl/android/maven2/group-id-with-slashes/artifact/version/filename

BASE="https://dl.google.com/dl/android/maven2"
MC="https://repo1.maven.org/maven2"

# AndroidX Core
echo "=== Downloading Core ==="
curl -sfL "$BASE/androidx/core/core-ktx/1.15.0/core-ktx-1.15.0.aar" -o /tmp/lib/core-ktx.aar && echo "OK core-ktx" || echo "SKIP core-ktx"
curl -sfL "$BASE/androidx/core/core/1.15.0/core-1.15.0.aar" -o /tmp/lib/core.aar && echo "OK core" || echo "SKIP core"
curl -sfL "$MC/androidx/annotation/annotation-jvm/1.9.1/annotation-jvm-1.9.1.jar" -o /tmp/lib/annotation.jar && echo "OK annotation" || echo "SKIP annotation"
curl -sfL "$BASE/androidx/annotation/annotation/1.9.1/annotation-1.9.1.aar" -o /tmp/lib/annotation.aar && echo "OK annotation-aar" || echo "SKIP annotation-aar"

echo "=== Downloading Lifecycle ==="
curl -sfL "$BASE/androidx/lifecycle/lifecycle-runtime-ktx/2.8.7/lifecycle-runtime-ktx-2.8.7.aar" -o /tmp/lib/lifecycle-runtime-ktx.aar || echo "SKIP"
curl -sfL "$BASE/androidx/lifecycle/lifecycle-runtime/2.8.7/lifecycle-runtime-2.8.7.aar" -o /tmp/lib/lifecycle-runtime.aar || echo "SKIP"
curl -sfL "$BASE/androidx/lifecycle/lifecycle-viewmodel/2.8.7/lifecycle-viewmodel-2.8.7.aar" -o /tmp/lib/lifecycle-viewmodel.aar || echo "SKIP"
curl -sfL "$BASE/androidx/lifecycle/lifecycle-viewmodel-compose/2.8.7/lifecycle-viewmodel-compose-2.8.7.aar" -o /tmp/lib/lifecycle-viewmodel-compose.aar || echo "SKIP"
curl -sfL "$BASE/androidx/lifecycle/lifecycle-livedata/2.8.7/lifecycle-livedata-2.8.7.aar" -o /tmp/lib/lifecycle-livedata.aar || echo "SKIP"
curl -sfL "$BASE/androidx/lifecycle/lifecycle-livedata-core/2.8.7/lifecycle-livedata-core-2.8.7.aar" -o /tmp/lib/lifecycle-livedata-core.aar || echo "SKIP"
curl -sfL "$BASE/androidx/lifecycle/lifecycle-viewmodel-savedstate/2.8.7/lifecycle-viewmodel-savedstate-2.8.7.aar" -o /tmp/lib/lifecycle-viewmodel-savedstate.aar || echo "SKIP"
curl -sfL "$BASE/androidx/lifecycle/lifecycle-common/2.8.7/lifecycle-common-2.8.7.jar" -o /tmp/lib/lifecycle-common.jar || echo "SKIP"

echo "=== Downloading Activity ==="
curl -sfL "$BASE/androidx/activity/activity/1.9.3/activity-1.9.3.aar" -o /tmp/lib/activity.aar || echo "SKIP"
curl -sfL "$BASE/androidx/activity/activity-compose/1.9.3/activity-compose-1.9.3.aar" -o /tmp/lib/activity-compose.aar || echo "SKIP"
curl -sfL "$BASE/androidx/activity/activity-ktx/1.9.3/activity-ktx-1.9.3.aar" -o /tmp/lib/activity-ktx.aar || echo "SKIP"

echo "=== Downloading Compose ==="
curl -sfL "$BASE/androidx/compose/runtime/runtime/1.7.6/runtime-1.7.6.aar" -o /tmp/lib/compose-runtime.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/runtime/runtime-saveable/1.7.6/runtime-saveable-1.7.6.aar" -o /tmp/lib/compose-runtime-saveable.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/ui/ui/1.7.6/ui-1.7.6.aar" -o /tmp/lib/compose-ui.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/ui/ui-geometry/1.7.6/ui-geometry-1.7.6.aar" -o /tmp/lib/compose-ui-geometry.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/ui/ui-graphics/1.7.6/ui-graphics-1.7.6.aar" -o /tmp/lib/compose-ui-graphics.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/ui/ui-text/1.7.6/ui-text-1.7.6.aar" -o /tmp/lib/compose-ui-text.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/ui/ui-unit/1.7.6/ui-unit-1.7.6.aar" -o /tmp/lib/compose-ui-unit.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/ui/ui-util/1.7.6/ui-util-1.7.6.aar" -o /tmp/lib/compose-ui-util.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/foundation/foundation/1.7.6/foundation-1.7.6.aar" -o /tmp/lib/compose-foundation.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/foundation/foundation-layout/1.7.6/foundation-layout-1.7.6.aar" -o /tmp/lib/compose-foundation-layout.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/animation/animation/1.7.6/animation-1.7.6.aar" -o /tmp/lib/compose-animation.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/animation/animation-core/1.7.6/animation-core-1.7.6.aar" -o /tmp/lib/compose-animation-core.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/material3/material3/1.3.1/material3-1.3.1.aar" -o /tmp/lib/compose-material3.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/material/material-icons-core/1.7.6/material-icons-core-1.7.6.aar" -o /tmp/lib/material-icons-core.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/material/material-icons-extended/1.7.6/material-icons-extended-1.7.6.aar" -o /tmp/lib/material-icons-extended.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/material/material/1.7.6/material-1.7.6.aar" -o /tmp/lib/compose-material.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/material/material-ripple/1.7.6/material-ripple-1.7.6.aar" -o /tmp/lib/compose-material-ripple.aar || echo "SKIP"

echo "=== Downloading Navigation ==="
curl -sfL "$BASE/androidx/navigation/navigation-compose/2.8.5/navigation-compose-2.8.5.aar" -o /tmp/lib/navigation-compose.aar || echo "SKIP"
curl -sfL "$BASE/androidx/navigation/navigation-runtime/2.8.5/navigation-runtime-2.8.5.aar" -o /tmp/lib/navigation-runtime.aar || echo "SKIP"
curl -sfL "$BASE/androidx/navigation/navigation-runtime-ktx/2.8.5/navigation-runtime-ktx-2.8.5.aar" -o /tmp/lib/navigation-runtime-ktx.aar || echo "SKIP"
curl -sfL "$BASE/androidx/navigation/navigation-common/2.8.5/navigation-common-2.8.5.aar" -o /tmp/lib/navigation-common.aar || echo "SKIP"
curl -sfL "$BASE/androidx/navigation/navigation-common-ktx/2.8.5/navigation-common-ktx-2.8.5.aar" -o /tmp/lib/navigation-common-ktx.aar || echo "SKIP"

echo "=== Downloading SavedState ==="
curl -sfL "$BASE/androidx/savedstate/savedstate/1.2.1/savedstate-1.2.1.aar" -o /tmp/lib/savedstate.aar || echo "SKIP"
curl -sfL "$BASE/androidx/savedstate/savedstate-ktx/1.2.1/savedstate-ktx-1.2.1.aar" -o /tmp/lib/savedstate-ktx.aar || echo "SKIP"

echo "=== Downloading Other AndroidX ==="
curl -sfL "$BASE/androidx/concurrent/concurrent-futures/1.2.0/concurrent-futures-1.2.0.jar" -o /tmp/lib/concurrent-futures.jar || echo "SKIP"
curl -sfL "$BASE/androidx/interpolator/interpolator/1.0.0/interpolator-1.0.0.aar" -o /tmp/lib/interpolator.aar || echo "SKIP"
curl -sfL "$BASE/androidx/loader/loader/1.0.0/loader-1.0.0.aar" -o /tmp/lib/loader.aar || echo "SKIP"
curl -sfL "$BASE/androidx/profileinstaller/profileinstaller/1.4.1/profileinstaller-1.4.1.aar" -o /tmp/lib/profileinstaller.aar || echo "SKIP"
curl -sfL "$BASE/androidx/startup/startup-runtime/1.1.1/startup-runtime-1.1.1.aar" -o /tmp/lib/startup-runtime.aar || echo "SKIP"
curl -sfL "$BASE/androidx/versionedparcelable/versionedparcelable/1.1.1/versionedparcelable-1.1.1.aar" -o /tmp/lib/versionedparcelable.aar || echo "SKIP"
curl -sfL "$BASE/androidx/collection/collection/1.4.5/collection-1.4.5.jar" -o /tmp/lib/collection.jar || echo "SKIP"
curl -sfL "$BASE/androidx/collection/collection-ktx/1.4.5/collection-ktx-1.4.5.jar" -o /tmp/lib/collection-ktx.jar || echo "SKIP"
curl -sfL "$BASE/androidx/arch/core/core-runtime/2.2.0/core-runtime-2.2.0.aar" -o /tmp/lib/core-runtime.aar || echo "SKIP"
curl -sfL "$BASE/androidx/arch/core/core-common/2.2.0/core-common-2.2.0.jar" -o /tmp/lib/core-common.jar || echo "SKIP"
curl -sfL "$BASE/androidx/tracing/tracing/1.2.0/tracing-1.2.0.aar" -o /tmp/lib/tracing.aar || echo "SKIP"
curl -sfL "$BASE/androidx/emoji2/emoji2/1.3.0/emoji2-1.3.0.aar" -o /tmp/lib/emoji2.aar || echo "SKIP"
curl -sfL "$BASE/androidx/customview/customview/1.0.0/customview-1.0.0.aar" -o /tmp/lib/customview.aar || echo "SKIP"
curl -sfL "$BASE/androidx/viewpager/viewpager/1.0.0/viewpager-1.0.0.aar" -o /tmp/lib/viewpager.aar || echo "SKIP"
curl -sfL "$BASE/androidx/slidingpanelayout/slidingpanelayout/1.2.0/slidingpanelayout-1.2.0.aar" -o /tmp/lib/slidingpanelayout.aar || echo "SKIP"
curl -sfL "$BASE/androidx/window/window/1.3.0/window-1.3.0.aar" -o /tmp/lib/window.aar || echo "SKIP"
curl -sfL "$BASE/androidx/window/extensions/window-extensions/1.0.0/window-extensions-1.0.0.aar" -o /tmp/lib/window-extensions.aar || echo "SKIP"
curl -sfL "$BASE/androidx/autofill/autofill/1.1.0/autofill-1.1.0.aar" -o /tmp/lib/autofill.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/ui/ui-tooling-preview/1.7.6/ui-tooling-preview-1.7.6.aar" -o /tmp/lib/compose-ui-tooling-preview.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/ui/ui-viewbinding/1.7.6/ui-viewbinding-1.7.6.aar" -o /tmp/lib/compose-ui-viewbinding.aar || echo "SKIP"
curl -sfL "$BASE/androidx/compose/runtime/runtime-livedata/1.7.6/runtime-livedata-1.7.6.aar" -o /tmp/lib/compose-runtime-livedata.aar || echo "SKIP"

echo "=== Downloading Material & AppCompat ==="
curl -sfL "$BASE/com/google/android/material/material/1.12.0/material-1.12.0.aar" -o /tmp/lib/material.aar || echo "SKIP"
curl -sfL "$BASE/androidx/appcompat/appcompat/1.7.0/appcompat-1.7.0.aar" -o /tmp/lib/appcompat.aar || echo "SKIP"
curl -sfL "$BASE/androidx/appcompat/appcompat-resources/1.7.0/appcompat-resources-1.7.0.aar" -o /tmp/lib/appcompat-resources.aar || echo "SKIP"
curl -sfL "$BASE/androidx/vectordrawable/vectordrawable/1.1.0/vectordrawable-1.1.0.aar" -o /tmp/lib/vectordrawable.aar || echo "SKIP"
curl -sfL "$BASE/androidx/vectordrawable/vectordrawable-animated/1.1.0/vectordrawable-animated-1.1.0.aar" -o /tmp/lib/vectordrawable-animated.aar || echo "SKIP"
curl -sfL "$BASE/androidx/fragment/fragment/1.5.4/fragment-1.5.4.aar" -o /tmp/lib/fragment.aar || echo "SKIP"
curl -sfL "$BASE/androidx/drawerlayout/drawerlayout/1.1.1/drawerlayout-1.1.1.aar" -o /tmp/lib/drawerlayout.aar || echo "SKIP"
curl -sfL "$BASE/androidx/coordinatorlayout/coordinatorlayout/1.1.0/coordinatorlayout-1.1.0.aar" -o /tmp/lib/coordinatorlayout.aar || echo "SKIP"
curl -sfL "$BASE/androidx/swiperefreshlayout/swiperefreshlayout/1.1.0/swiperefreshlayout-1.1.0.aar" -o /tmp/lib/swiperefreshlayout.aar || echo "SKIP"
curl -sfL "$BASE/androidx/recyclerview/recyclerview/1.1.0/recyclerview-1.1.0.aar" -o /tmp/lib/recyclerview.aar || echo "SKIP"
curl -sfL "$BASE/androidx/transition/transition/1.5.0/transition-1.5.0.aar" -o /tmp/lib/transition.aar || echo "SKIP"
curl -sfL "$BASE/androidx/viewpager2/viewpager2/1.1.0/viewpager2-1.1.0.aar" -o /tmp/lib/viewpager2.aar || echo "SKIP"
curl -sfL "$BASE/androidx/cardview/cardview/1.0.0/cardview-1.0.0.aar" -o /tmp/lib/cardview.aar || echo "SKIP"
curl -sfL "$BASE/androidx/constraintlayout/constraintlayout/2.2.0/constraintlayout-2.2.0.aar" -o /tmp/lib/constraintlayout.aar || echo "SKIP"
curl -sfL "$BASE/androidx/constraintlayout/constraintlayout-core/1.1.0/constraintlayout-core-1.1.0.jar" -o /tmp/lib/constraintlayout-core.jar || echo "SKIP"

echo "=== Downloading libsu ==="
curl -sfL "$MC/com/github/topjohnwu/libsu/core/5.2.2/core-5.2.2.aar" -o /tmp/lib/libsu-core.aar || echo "SKIP"
curl -sfL "$MC/com/github/topjohnwu/libsu/service/5.2.2/service-5.2.2.aar" -o /tmp/lib/libsu-service.aar || echo "SKIP"
curl -sfL "$MC/com/github/topjohnwu/libsu/nio/5.2.2/nio-5.2.2.aar" -o /tmp/lib/libsu-nio.aar || echo "SKIP"
curl -sfL "$MC/com/github/topjohnwu/libsu/io/5.2.2/io-5.2.2.aar" -o /tmp/lib/libsu-io.aar || echo "SKIP"

echo "=== Done ==="
ls -la /tmp/lib/ | wc -l
ls -la /tmp/lib/ | head -50
